name: glimmer CI/CD

# 当 main 分支有更新时触发
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # 云端虚拟机

    steps:
    # 1 克隆仓库代码
    - name: 克隆仓库
      uses: actions/checkout@v3

    # 2 清空我服务器上旧残留内容
    - name: 清空服务器旧内容
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          rm -rf /home/ubuntu/project/glimmer/homepage/*
          rm -rf /home/ubuntu/project/glimmer/recruit/*
          rm -rf /home/ubuntu/project/glimmer/submit/*
          rm /home/ubuntu/project/glimmer/docker-compose.yml
          rm /home/ubuntu/project/glimmer/nginx.conf
          rmdir /home/ubuntu/project/glimmer/homepage
          rmdir /home/ubuntu/project/glimmer/recruit
          rmdir /home/ubuntu/project/glimmer/submit
    
    # 3.1 上传前端资源-homepage
    - name: 上传前端资源-homepage
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        source: "homepage/*"
        target: "/home/ubuntu/project/glimmer/"

    # 3.2 上传前端资源-recruit
    - name: 上传前端资源-recruit
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        source: "recruit/*"
        target: "/home/ubuntu/project/glimmer/"

    # 3.3 上传前端资源-submit
    - name: 上传前端资源-submit
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        source: "submit/*"
        target: "/home/ubuntu/project/glimmer/"
    
    # 4 上传 docker-compose.yml
    - name: 上传 docker 配置
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        source: "docker-compose.yml"
        target: "/home/ubuntu/project/glimmer/"
    
    # 5 上传 nginx.conf
    - name: 上传 nginx 配置
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        source: "nginx.conf"
        target: "/home/ubuntu/project/glimmer/"
    
    # 6 SSH 登录服务器并重启 Docker Compose 容器
    - name: 重启 Docker Compose 容器
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/project/glimmer/
          docker compose up -d
